// when you first install helix, you MUST do this FIRST!

hx --grammar fetch to fetch the grammars and hx --grammar build to build them!

// then, check rust!
hx --health rust

if it failes, check the rust analyzer!
rust-analyzer --version

// then install!
rustup component add rust-analyzer


theme = "dark_plus"

[editor]
line-number = "relative"
auto-completion = true
idle-timeout = 0
completion-trigger-len = 2
auto-info = true # this shows the help shortcut sections
auto-format = true
true-color = true
color-modes = true
bufferline = "multiple"
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
mouse = true 
middle-click-paste = true   
insert-final-newline = true
shell = ["nu", "-c"]
continue-comments = false
completion-timeout = 250
preview-completion-insert	= true
text-width = 80
popup-border = "all"


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
w = { w = [":pipe echo 'println!(\"DEBUG this is {:#?}\",);'","goto_line_end","move_char_left"]}
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.select]
Q = ":x"
G = "goto_file_end"

"space" = {v = "vsplit", q = [":w",":bc!"]}

g = {c = "toggle_comments", a = "code_action", n = "jump_view_left", o =  "jump_view_right", j = "jump_view_down", k = "jump_view_up", b = "jump_backward", f = "jump_forward", t = "goto_prev_diag", u = "goto_next_diag", h = [":format",":w"]}

y = ["yank_main_selection_to_clipboard", "normal_mode"]
p = ["paste_clipboard_after", "normal_mode"]
P = ["replace_selections_with_clipboard", "normal_mode"] 
d = ["yank_main_selection_to_clipboard", "delete_selection"]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"." = "repeat_last_motion"
"%" = "match_brackets"
V = ["select_mode", "select_line_below", "extend_to_line_bounds"]

[keys.normal]
"C-v" = ":config-reload"
"C-o" = ":config-open"

V = ["select_mode", "select_line_below", "extend_to_line_bounds"]
"." = "repeat_last_motion"

Q = ":x"
p = ["paste_clipboard_after", "normal_mode"]
P = ["replace_selections_with_clipboard", "normal_mode"] 
y = ["yank_main_selection_to_clipboard", "normal_mode"]
d = ["yank_main_selection_to_clipboard", "delete_selection"]
"%" = "match_brackets"
G = "goto_file_end"
Z = ["half_page_down"]
X = ["half_page_up"]

w = ["move_next_word_start", "move_char_right", "collapse_selection"]
W = ["move_next_long_word_start", "move_char_right", "collapse_selection"]
e = ["move_next_word_end", "collapse_selection"]
E = ["move_next_long_word_end", "collapse_selection"]
b = ["move_prev_word_start", "collapse_selection"]
B = ["move_prev_long_word_start", "collapse_selection"]
u = ["undo", "collapse_selection"]

"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

q = ["move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "align_view_center"]
t = ["move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "align_view_center"]

"space" = {v = "vsplit", q = [":w",":bc!"], a = [":w", ":sh nu -c /Users/jasonjurotich/gits.nu"], e = ":show-directory"}

g = {c = "toggle_comments", a = "code_action", n = "jump_view_left", o =  "jump_view_right", j = "jump_view_down", k = "jump_view_up", b = "jump_backward", f = "jump_forward", t = "goto_prev_diag", u = "goto_next_diag", h = [":format",":w"]}


"tab" = ":bn"
"S-tab" = ":bp"

esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

m = {t = ["goto_first_nonwhitespace", "select_mode", "goto_line_end", "surround_add"]}

[editor.statusline]
# file path can be file-absolute-path or file-name or file-base-name
left = ["mode", "file-name", "file-modification-indicator", "spacer", "spinner"]
center = []
right = ["diagnostics","workspace-diagnostics"]
separator = "│"

[editor.lsp]
display-progress-messages = true
display-messages = true
display-inlay-hints = true
auto-signature-help = true
display-signature-help-docs = true
snippets = true


[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"

[editor.soft-wrap]
enable = true
max-wrap = 20
max-indent-retain = 40
wrap-at-text-width = false

# you can only have single pairs for now 
[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
"'" = "'"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.smart-tab]
enable = true

[editor.whitespace.render]
space = "none"
tab = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.file-picker]
hidden = false
ignore = true


[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 10000

[editor.search]
wrap-around = true
