# https://blog.getreu.net/20220828-tp-note-new8/
# https://medium.com/@CaffeineForCode/helix-setup-for-markdown-b29d9891a812
# https://github.com/helix-editor/helix/discussions/3637#discussioncomment-6868540
# https://github.com/helix-editor/helix/issues/7149
# https://roderik.no/helix-editor-with-multiple-lsps-for-one-language



[[language]]
name = "markdown"
language-servers = ["ltex-ls" ]
file-types = ["md", "txt"]
scope = "source.md"
indent = { tab-width = 2, unit = "  " }
injection-regex = "md|markdown"
auto-format = true
# roots = [".git"]

[language-server.ltex-ls]
config = { ltex.language = "en-US" }
# config = { ltex = {language = "en-US", language = "es-MX"} }
# [language-server.ltex.config.ltex.dictionary]
# "en-US" = ["Tp-Note","Zettelkasten"]
# {"en-US", "es-MX"}

[[language]]
name = "sql"
language-servers = ["sql"]
file-types = ["sql"]
scope = "source.sql"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[language-server.sql]
command = "/opt/homebrew/bin/sql-language-server"

[[language]]
name = "rust"

[language-server.rust-analyzer.config]
checkOnSave = {command = "clippy"}
# checkOnSave = {command = "clippy", extraArgs = ["--", "-W", "clippy::pedantic"]}

[language.debugger]
name = "lldb-vscode"
transport = "stdio"
command = "lldb-vscode"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
# args = { program = "{0}", runInTerminal = true }
args = { program = "{0}"}

# scope = "source.rust"
# injection-regex = "rust"
# file-types = ["rs"]
# roots = ["Cargo.toml", "Cargo.lock"]
# auto-format = true
# comment-token = "//"
# language-server = { command = "rust-analyzer" }
# indent = { tab-width = 2, unit = "  " }
